services:
  - type: web
    name: streamlit-app-llm
    runtime: python
    repo: https://github.com/rick020/streamlit-render
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0
    region: frankfurt
    envVars:
    - key: OLLAMA_URL
      fromService:
        name: ollama-server
        type: pserv
        property: hostport

  - type: pserv
    name: ollama-server
    runtime: docker
    dockerContext: ./ollama
    dockerfilePath: ./ollama/Dockerfile
    region: frankfurt
    plan: starter  # or standard, depending on your needs
