services:
  - type: web
    name: ollama-server
    env: docker
    plan: starter  # or standard, depending on your needs
    disk:
      name: ollama-models
      mountPath: /root/.ollama
      sizeGB: 10