services:
  - type: pserv
    name: ollama-server
    image:
      url: docker.io/ollama/ollama
    runtime: docker
    region: frankfurt
    plan: starter  # or standard, depending on your needs
    disk:
      name: ollama-models
      mountPath: /root/.ollama
      sizeGB: 10