services:
  - type: pserv
    runtime: docker
    name: ollama-server
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: starter  # or standard, depending on your needs
    disk:
      name: ollama-models
      mountPath: /root/.ollama
      sizeGB: 10